const path = require("path");
const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "MS App",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:4000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Google Auth",
      description: "Endpoints",
    },
    {
      name: "Google Calendar",
      description: "Endpoints",
    },
    {
      name: "Company",
      description: "Endpoints",
    },
    {
      name: "Holiday",
      description: "Endpoints",
    },
    {
      name: "Leave",
      description: "Endpoints",
    },
    {
      name: "Project",
      description: "Endpoints",
    },
    {
      name: "Report",
      description: "Endpoints",
    },
    {
      name: "Task",
      description: "Endpoints",
    },
    {
      name: "Timelog",
      description: "Endpoints",
    },
    {
      name: "Todo",
      description: "Endpoints",
    },
    {
      name: "Training",
      description: "Endpoints",
    },
  ],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = [
  path.join(__dirname, "src/routes/google/gAuth.ts"),
  path.join(__dirname, "src/routes/google/gCalendar.ts"),
  path.join(__dirname, "src/routes/company.ts"),
  path.join(__dirname, "src/routes/holiday.ts"),
  path.join(__dirname, "src/routes/leave.ts"),
  path.join(__dirname, "src/routes/project.ts"),
  path.join(__dirname, "src/routes/reports.ts"),
  path.join(__dirname, "src/routes/task.ts"),
  path.join(__dirname, "src/routes/timelog.ts"),
  path.join(__dirname, "src/routes/todo.ts"),
  path.join(__dirname, "src/routes/training.ts"),
];

swaggerAutogen(outputFile, endpointsFiles, doc);
